import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import QueryProvider from "@/lib/query-client";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      
      <html lang="en">
  
      <QueryProvider>
        <body>
         
          {children}
        </body>
        </QueryProvider>
       
      </html>

      
    
  );
}
