// Add this at the top to make it a Client Component
import type { Metadata } from "next";

import "./globals.css";
import store from "./store/store";
import { Provider } from 'react-redux';
import StoreProvider from "@/lib/store-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import QueryProvider from "@/lib/query-client";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <StoreProvider>
      <html lang="en">
  
      <QueryProvider>
        <body>
         
          {children}
        </body>
        </QueryProvider>
       
      </html>
      </StoreProvider>

      
    
  );
}
